---

- hosts: webservers
  become: true
  tasks:
    - name: Install required packages
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - git
        - docker
        - httpd
