---
- hosts: webservers
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install webserver
      package:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2'}}"
        state: present
    - name: start and enable
      service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2'}}"
        state: started
        enabled: yes
    - name: Install git
      package:
        name: git
        state: present
    - name: deploy static website from git
      git:
        repo: https://github.com/javahometech/javahome-app
        dest: /var/www/html
        force: yes
    - name: change port number of apache
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen "{{apachePort}}"
      notify:
        - restart apache server
  handlers:
    - name: restart apache server
      service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2'}}"
        state: restarted
