---
- hosts: 172.31.7.6
  become: yes
  tasks:
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: Start and enable docker
      service:
        name: docker
        state: started
        enabled: yes
